#' Plot DTU Candidates Heatmap
#'
#' @description
#' Generates a heatmap of cluster markers restricted to the identified DTU candidates.
#'
#' @param cotan_obj A `COTAN` object.
#' @param dtu_candidates A data.frame generated by `extract_dtu_candidates()`.
#'
#' @return A ggplot object containing the heatmap, or NULL if no candidates are provided.
#'
#' @importFrom COTAN clustersMarkersHeatmapPlot
#' @export
plot_dtu_heatmap <- function(cotan_obj, dtu_candidates) {
    log_header("Generating DTU Heatmap")
    
    if (nrow(dtu_candidates) == 0) {
        log_warn("No DTU candidates provided. Skipping heatmap generation.")
        return(NULL)
    }

    log_info("Extracting unique transcript features...")
    unique_transcripts <- unique(c(dtu_candidates$Transcript_A, dtu_candidates$Transcript_B))
    
    log_cotan_execution("clustersMarkersHeatmapPlot()")
    heatmap_plot <- COTAN::clustersMarkersHeatmapPlot(cotan_obj, features = unique_transcripts)
    log_cotan_execution("clustersMarkersHeatmapPlot()", is_complete = TRUE)
    
    log_stat("Status: DTU Heatmap generated successfully.")
    log_header("Generating DTU Heatmap Complete", is_complete = TRUE)
    
    return(heatmap_plot)
}
