# Seurat QC and Filtering Module

#' Create a Toy Subset of a Seurat Object
#'
#' @description
#' Randomly subsets a Seurat object to a specified number of features and cells.
#' This is useful for rapid testing, debugging, and sanity checks as suggested.
#'
#' @param seurat_obj A `Seurat` object.
#' @param num_features Integer. Number of random features (transcripts) to retain. Default is 10000.
#' @param num_cells Integer. Number of random cells to retain. Default is 8000.
#' @param seed Integer. Random seed for reproducibility. Default is 42.
#'
#' @return A randomly subsetted `Seurat` object.
#'
#' @importFrom SeuratObject Features Cells
#' @export
create_test_subset <- function(seurat_obj, num_features = 10000, num_cells = 8000, seed = 42) {
  log_header("Creating Test Subset")

  set.seed(seed)

  all_features <- SeuratObject::Features(seurat_obj)
  all_cells <- SeuratObject::Cells(seurat_obj)

  if (num_features > length(all_features) || num_cells > length(all_cells)) {
    log_warn(
      "The requested subset parameters are larger than the original. The entire available dataset will be returned."
    )
  }

  actual_features_to_keep <- min(num_features, length(all_features))
  actual_cells_to_keep <- min(num_cells, length(all_cells))

  log_info(sprintf("Sampling %d random features (out of %d)...", actual_features_to_keep, length(all_features)))
  sampled_features <- sample(all_features, actual_features_to_keep)

  log_info(sprintf("Sampling %d random cells (out of %d)...", actual_cells_to_keep, length(all_cells)))
  sampled_cells <- sample(all_cells, actual_cells_to_keep)

  log_info("Subsetting Seurat object...")
  seurat_subset <- subset(seurat_obj, features = sampled_features, cells = sampled_cells)

  log_info("Subset created successfully.")
  log_stat(sprintf("%d cells", ncol(seurat_subset)))
  log_stat(sprintf("%d features", nrow(seurat_subset)))

  log_header("Subset Complete", is_complete = TRUE)

  return(seurat_subset)
}

#' Round Seurat Raw Counts to Integers
#'
#' @description
#' Extracts the raw sparse matrix from a Seurat object, rounds all values to the
#' nearest integer, and replaces the assay data. This is crucial for models like
#' COTAN that expect discrete count data (Poisson/Negative Binomial).
#' It automatically drops explicit zeros generated by rounding down values < 0.5.
#'
#' @param seurat_obj A `Seurat` object.
#' @param assay Character. The assay to use. Default is "RNA".
#'
#' @return A `Seurat` object with strictly integer counts.
#'
#' @importFrom Seurat GetAssayData SetAssayData
#' @importFrom Matrix drop0
#' @export
round_seurat_counts <- function(seurat_obj, assay = "RNA") {
  log_header("Rounding Seurat Counts")

  log_info(sprintf("Extracting counts from assay '%s'...", assay))
  raw_matrix <- Seurat::GetAssayData(seurat_obj, assay = assay, layer = "counts")

  log_info("Rounding decimal values to integers...")
  raw_matrix@x <- round(raw_matrix@x)

  log_info("Dropping explicit zeros...")
  raw_matrix <- Matrix::drop0(raw_matrix)

  log_info("Updating Seurat object with rounded counts...")
  seurat_obj <- Seurat::SetAssayData(
    seurat_obj,
    layer = "counts",
    new.data = raw_matrix,
    assay = assay
  )

  log_header("Rounding Complete", is_complete = TRUE)

  return(seurat_obj)
}

#' Filter Seurat Object to Retain Only Spliced Transcripts
#'
#' @description
#' Filters the features of a Seurat object to keep only those that match a specific
#' prefix. This is used to retain mature, spliced transcripts (e.g., "ENST")
#' and discard unspliced/intronic regions (e.g., "ENSG").
#'
#' @param seurat_obj A `Seurat` object.
#' @param prefix Character string. The regex prefix to match spliced transcripts. Default is "^ENST".
#'
#' @return A new, filtered `Seurat` object containing only the matched features.
#'
#' @importFrom SeuratObject Features
#' @export
filter_spliced_transcripts <- function(seurat_obj, prefix = "^ENST") {
  log_header("Transcript Type Filtering")

  all_features <- SeuratObject::Features(seurat_obj)
  num_features_before <- length(all_features)

  log_info(sprintf("Retaining only features matching prefix '%s'...", prefix))

  spliced_features <- grep(prefix, all_features, value = TRUE)
  num_features_after <- length(spliced_features)

  if (num_features_after == 0) {
    log_error("No features match the provided prefix. Check your matrix row names.", stop_exec = FALSE)
  }

  if (num_features_after < (num_features_before * 0.05)) {
    log_warn(sprintf(
      "Extreme filtering detected. Less than 5%% of features retained. Is the prefix '%s' correct for this species?",
      prefix
    ))
  }

  seurat_filtered <- subset(seurat_obj, features = spliced_features)

  log_info("Filtering complete.")
  log_stat(sprintf("Features before: %d", num_features_before))
  log_stat(sprintf("Features removed: %d", (num_features_before - num_features_after)))
  log_stat(sprintf("Features remaining: %d", num_features_after))

  log_header("Filtering Complete", is_complete = TRUE)

  return(seurat_filtered)
}

#' Filter Seurat Object to Remove Empty Droplets
#'
#' @description
#' Filters out cells from a Seurat object that have zero RNA counts, effectively removing empty
#' droplets from the dataset. This is a preliminary quality control step to ensure that only cells
#' with detectable RNA are retained for downstream analysis.
#' @param seurat_obj A `Seurat` object containing single-cell RNA-seq data.
#' @return A new `Seurat` object with empty droplets removed.
#' @export
filter_empty_droplets <- function(seurat_obj) {
  log_header("Empty Droplet Filtering")

  log_info("Filtering completely empty droplets...")
  seurat_filtered <- subset(seurat_obj, subset = nCount_RNA > 0) # nolint: object_usage_linter.

  num_cells_before <- ncol(seurat_obj)
  num_cells_after <- ncol(seurat_filtered)

  log_info("Filtering complete.")
  log_stat(sprintf("Cells before: %d", num_cells_before))
  log_stat(sprintf("Cells removed: %d", (num_cells_before - num_cells_after)))
  log_stat(sprintf("Cells remaining: %d", num_cells_after))

  log_header("Filtering Complete", is_complete = TRUE)

  return(seurat_filtered)
}

#' Filter Seurat Object by Mitochondrial Transcript Percentage
#'
#' @description
#' Calculates the percentage of mitochondrial counts per cell using a custom
#' list of transcript IDs and filters out cells exceeding a specified threshold.
#'
#' @param seurat_obj A `Seurat` object containing single-cell RNA-seq data.
#' @param mt_transcripts_list A character vector containing transcript IDs.
#' @param threshold Numeric. Maximum acceptable MT percentage. Default is 5.
#'
#' @return A new, filtered `Seurat` object. It has an additional metadata column `percent.mt`
#' representing the percentage of mitochondrial counts per cell.
#'
#' @importFrom Seurat PercentageFeatureSet
#' @importFrom SeuratObject Features
#' @export
filter_mt_transcripts <- function(seurat_obj, mt_transcripts_list, threshold = 5) {
  log_header("Mitochondrial Filtering")

  valid_mt <- base::intersect(mt_transcripts_list, SeuratObject::Features(seurat_obj))
  log_stat(sprintf("Valid mitochondrial transcripts: %d", length(valid_mt)))

  if (length(valid_mt) == 0) {
    log_error("No mitochondrial transcripts found in the matrix. Check that the ID format matches the Seurat rownames.",
      stop_exec = TRUE
    )
  }

  log_info(sprintf("Filtering cells with MT counts >= %s%%...", threshold))

  seurat_obj[["percent.mt"]] <- Seurat::PercentageFeatureSet(
    seurat_obj,
    features = valid_mt,
    assay = "RNA"
  )

  num_cells_before <- ncol(seurat_obj)
  seurat_filtered <- subset(seurat_obj, subset = percent.mt < threshold) # nolint: object_usage_linter.
  num_cells_after <- ncol(seurat_filtered)

  log_info("Filtering complete.")
  log_stat(sprintf("Cells before: %d", num_cells_before))
  log_stat(sprintf("Cells removed: %d", (num_cells_before - num_cells_after)))
  log_stat(sprintf("Cells remaining: %d", num_cells_after))

  log_header("Filtering Complete", is_complete = TRUE)

  return(seurat_filtered)
}

#' Iteratively Filter Sparse Matrix in Seurat Object
#'
#' @description
#' Extracts the raw sparse matrix from a Seurat object and iteratively applies
#' cutoffs for minimum expressing cells per gene and minimum expressed genes per cell.
#' It loops on the dgCMatrix until convergence (zero features or cells dropped).
#'
#' @param seurat_obj A `Seurat` object.
#' @param cells_cutoff Numeric. Fraction of cells a feature must be expressed in. Default is 0.003.
#' @param genes_cutoff Numeric. Fraction of features a cell must express. Default is 0.002.
#' @param loss_threshold Numeric. Threshold (0-1) to trigger a warning for data loss. Default is 0.5 (50%).
#'
#' @return A new, subsetted `Seurat` object with the converged dimensions.
#'
#' @importFrom Seurat GetAssayData
#' @importFrom Matrix drop0
#' @export
filter_iterative_sparsity <- function(seurat_obj, cells_cutoff = 0.003, genes_cutoff = 0.002, loss_threshold = 0.5) {
  log_header("Iterative Sparsity Filtering")

  log_stat(sprintf("Cells cutoff: %f", cells_cutoff))
  log_stat(sprintf("Genes cutoff: %f", genes_cutoff))

  raw_mat <- Seurat::GetAssayData(seurat_obj, assay = "RNA", layer = "counts")
  raw_mat <- Matrix::drop0(raw_mat)

  initial_features <- nrow(raw_mat)
  initial_cells <- ncol(raw_mat)

  converged <- FALSE
  iteration <- 1

  while (!converged) {
    log_info(sprintf("Iteration %d...", iteration))
    start_genes <- nrow(raw_mat)
    start_cells <- ncol(raw_mat)

    # Filter genes
    absolute_gene_cutoff <- round(start_cells * cells_cutoff, digits = 0L)
    expressing_cells <- tabulate(raw_mat@i + 1L, nbins = start_genes)
    raw_mat <- raw_mat[expressing_cells > absolute_gene_cutoff, , drop = FALSE]

    # Filter cells
    absolute_cell_cutoff <- round(nrow(raw_mat) * genes_cutoff, digits = 0L)
    expressed_genes <- diff(raw_mat@p)
    raw_mat <- raw_mat[, expressed_genes > absolute_cell_cutoff, drop = FALSE]

    end_genes <- nrow(raw_mat)
    end_cells <- ncol(raw_mat)

    if (end_genes == 0 || end_cells == 0) {
      log_error(
        "Iterative filtering removed ALL cells or ALL features. Reduce the cells_cutoff or genes_cutoff values.",
        stop_exec = TRUE
      )
    }

    dropped_g <- start_genes - end_genes
    dropped_c <- start_cells - end_cells

    log_info(sprintf("Iteration %d finished.", iteration))
    log_stat(sprintf("Cells before: %d", start_cells))
    log_stat(sprintf("Cells removed: %d", dropped_c))
    log_stat(sprintf("Cells remained: %d", end_cells))
    log_stat(sprintf("Features before: %d", start_genes))
    log_stat(sprintf("Features removed: %d", dropped_g))
    log_stat(sprintf("Features remained: %d", end_genes))


    if (dropped_g == 0 && dropped_c == 0) {
      converged <- TRUE
    } else {
      iteration <- iteration + 1
    }
  }

  final_features <- nrow(raw_mat)
  final_cells <- ncol(raw_mat)

  feature_loss_ratio <- (initial_features - final_features) / initial_features
  cell_loss_ratio <- (initial_cells - final_cells) / initial_cells

  if (feature_loss_ratio > loss_threshold) {
    log_warn(sprintf("High feature loss detected! Removed %.1f%% of total features.", feature_loss_ratio * 100))
  }

  if (cell_loss_ratio > loss_threshold) {
    log_warn(sprintf("High cell loss detected! Removed %.1f%% of total cells.", cell_loss_ratio * 100))
  }

  log_info("Filtering converged.")
  log_stat(sprintf("Cells before: %d", initial_cells))
  log_stat(sprintf("Cells removed: %d", initial_cells - final_cells))
  log_stat(sprintf("Cells remained: %d", final_cells))
  log_stat(sprintf("Features before: %d", initial_features))
  log_stat(sprintf("Features removed: %d", initial_features - final_features))
  log_stat(sprintf("Features remained: %d", final_features))

  valid_features <- rownames(raw_mat)
  valid_cells <- colnames(raw_mat)

  log_info("Updating Seurat Object...")
  seurat_filtered <- subset(seurat_obj, features = valid_features, cells = valid_cells)

  log_header("Filtering Complete", is_complete = TRUE)

  return(seurat_filtered)
}
